# notification-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: registrymicro.azurecr.io/notification-service:latest  # Replace with your image name
        ports:
        - containerPort: 5003
        env:
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "5003"

---

# notification-service Internal Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
  type: ClusterIP

---

# notification-service External Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: notification-service-external
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
  type: LoadBalancer
