name: CI/CD Pipeline

# Triggers the workflow on push to main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the OS for the VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code

      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
